name: flutter_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  english_words: ^3.1.0
  dio: ^3.0.6 #latest version
#  base_library:
#    git:
#      url: git://github.com/Sky24n/FlutterRepos.git
#      path: base_library

  date_format: "^1.0.4"
  # 汉字转拼音库 https://github.com/flutterchina/lpinyin
  lpinyin: ^1.0.7
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  #  common_utils: ^1.1.1
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  #  flustars: ^0.2.5+1
  # Flutter 国际化/多语言库 https://github.com/Sky24n/fluintl
  #  fluintl: ^0.1.3
  # Flutter 城市列表 https://github.com/flutterchina/azlistview
  azlistview: ^0.1.1


  # rxdart https://github.com/ReactiveX/rxdart
  rxdart: ^0.22.6
  # https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^1.1.3
  # https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^5.2.7
  # https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: 1.1.6
  # device_info
  #  device_info: ^0.4.0+1
  # webview_flutter
  webview_flutter: ^0.3.16
  # share
  share: ^0.6.3+3
  # https://github.com/flutterchina/flukit.
  flukit: ^1.0.2

  # Flutter 全局屏幕适配。https://github.com/flutterchina/auto_size
  # 如果有问题请尝试修改如下链接
  # url: https://github.com/flutterchina/auto_size.git
#  auto_size:
#    git:
#      url: git://github.com/flutterchina/auto_size.git

  fluttertoast: ^3.1.3
  json_annotation: ^3.0.0
  flutter_redux: ^0.5.3
  package_info: 0.4.0+6
  connectivity: 0.4.4
  flutter_markdown: 0.3.0
  flutter_spinkit: ^4.0.0
  flutter_webview_plugin: ^0.3.8
  sqflite: ^1.1.7+1
  path: ^1.7.0
  pub_semver: ^1.4.2
  flutter_svg: ^0.14.2
  flutter_slidable: ^0.5.3
  event_bus:  ^1.1.0
  flutter_cache_manager: ^1.1.1
  path_provider: ^1.3.0
  permission_handler: 3.2.2
  scoped_model: ^1.0.1
  bezier: ^1.1.2
  provider: ^3.1.0
  flare_flutter: ^1.6.1
  # 固定版本
  device_info: 0.4.0+3
  android_intent: 0.3.0
  shared_preferences: 0.5.3+4
  built_value: ^6.8.2
  graphql: ^2.0.0
  flutter_json_widget: 1.0.2
  flutter_localizations:
    sdk: flutter
  photo_view:
    git:
      url: https://github.com/CarSmallGuo/photo_view.git
      ref: master
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/lake.jpg
    - assets/images/found.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
